#!/usr/bin/env python3
"""Authored ingredient quantities (grams) for the Nepal Bagmati pack.

The pack originally carried a placeholder `100` g for every ingredient line in every
recipe, which made cost, protein and any derived grocery requirement meaningless.
These are real quantities for a household of four, matching each recipe's `servings`.

Keyed by recipe id, then ingredient id. A value may be a list when the recipe lists the
same ingredient twice; the entries are summed (e.g. malpuwa's two cardamom steps).

Keep in sync with generate_recipe_cost_protein.py, which validates this table covers
every ingredient line in recipes.json.
"""

QUANTITIES_GRAMS = {
    # --- dal ---
    "kalo-dal-jimbu": {"kalo_dal": 200, "jimbu": 10, "ghee": 30, "garlic": 20, "ginger": 10, "turmeric": 5},
    "musuro-dal-tadka": {"masuro_dal": 200, "mustard_oil": 30, "cumin": 5, "garlic": 15, "turmeric": 5, "tomato": 100},
    "rahar-dal-sadha": {"rahar_dal": 200, "ghee": 30, "cumin": 5, "turmeric": 5, "ginger": 10},
    "mung-dal-soup": {"mung_dal": 180, "ghee": 25, "cumin": 5, "ginger": 10, "turmeric": 5},
    "chana-dal-tarkari": {"chana": 200, "mustard_oil": 30, "onion": 100, "garlic": 15, "tomato": 120},
    "pancha-dal-mix": {"kalo_dal": 80, "masuro_dal": 80, "rahar_dal": 80, "mung_dal": 80, "chana": 80},
    "kwati-jhol": {"kwati_mix": 200, "mustard_oil": 30, "ajwain": 3, "ginger": 15, "garlic": 15, "ghee": 20},
    "bhatmas-jhol": {"bhatmas": 150, "mustard_oil": 25, "garlic": 15, "tomato": 120, "timur": 2},
    "simi-dal-jhol": {"french_beans": 250, "garlic": 15, "mustard_oil": 25, "jimbu": 5, "turmeric": 5},
    "masyaura-dal-jhol": {"masyaura": 120, "masuro_dal": 120, "mustard_oil": 25, "garlic": 15},
    "gundruk-bhatmas-jhol": {"gundruk": 150, "bhatmas": 120, "mustard_oil": 25, "garlic": 15, "tomato": 100},
    "kalo-dal-lahsun-chhop": {"kalo_dal": 200, "garlic": 30, "mustard_oil": 25, "red_chili": 5},
    "karkalo-dal": {"colocasia_leaves": 250, "masuro_dal": 120, "mustard_oil": 25, "garlic": 15},
    "chana-lauka-dal": {"chana": 180, "bottle_gourd": 400, "mustard_oil": 25, "ginger": 10},
    "palungo-dal": {"spinach": 200, "mung_dal": 120, "ghee": 25, "cumin": 5},
    # --- bhat ---
    "sada-bhat": {"rice": 300},
    "taichin-bhat": {"rice": 300},
    "maghe-khichadi": {"rice": 250, "kalo_dal": 100, "ghee": 40, "ginger": 15, "turmeric": 5},
    "jaulo-ayurvedic": {"rice": 250, "mung_dal": 80, "ghee": 35, "turmeric": 5, "ajwain": 2},
    "nepali-pulao": {"rice": 300, "ghee": 60, "green_peas": 100, "cardamom": 4, "cinnamon": 2},
    "bhuttuko-bhat": {"rice": 300, "mustard_oil": 25, "onion": 100, "turmeric": 5, "green_chili": 10},
    "kodo-ko-dhido": {"millet_flour": 200, "ghee": 30},
    "phapar-ko-dhido": {"buckwheat_flour": 220, "ghee": 30},
    "makai-ko-dhido": {"wheat_flour": 200, "ghee": 30},
    "bhatmas-chiura": {"chiura": 300, "bhatmas": 100, "mustard_oil": 20, "green_chili": 10},
    "khaja-chiura-tarkari": {"chiura": 250, "potato": 300, "green_peas": 100, "mustard_oil": 25},
    "dahi-chiura-kera": {"chiura": 250, "yogurt": 300},
    # --- tarkari ---
    "aloo-gobi-tarkari": {"potato": 400, "cauliflower": 400, "tomato": 200, "mustard_oil": 40, "ginger": 15, "garlic": 15},
    "aloo-kerau-tarkari": {"potato": 400, "green_peas": 200, "tomato": 200, "mustard_oil": 35, "cumin": 5},
    "aloo-tama-bodi": {"potato": 300, "bamboo_shoot": 200, "bodi": 150, "mustard_oil": 35, "garlic": 15},
    "aloo-dum-nepali": {"potato": 500, "mustard_oil": 40, "garlic": 25, "timur": 3, "red_chili": 5},
    "aloo-simi-tarkari": {"potato": 400, "french_beans": 250, "tomato": 180, "mustard_oil": 35},
    "aloo-bhendi-bhutuwa": {"potato": 300, "lady_finger": 250, "mustard_oil": 35, "cumin": 5},
    "bhendi-bhutuwa": {"lady_finger": 400, "mustard_oil": 40, "turmeric": 5, "fenugreek_seeds": 2},
    "chana-aloo-tarkari": {"chana": 150, "potato": 400, "mustard_oil": 35, "tomato": 180, "ginger": 15},
    "ghiraula-chana-tarkari": {"sponge_gourd": 400, "chana": 150, "mustard_oil": 35, "turmeric": 5},
    "lauka-ko-tarkari": {"bottle_gourd": 500, "mustard_oil": 30, "cumin": 5, "ginger": 10},
    "tito-karela-bhutuwa": {"bitter_gourd": 400, "mustard_oil": 40, "turmeric": 5, "salt": 10},
    "karela-aloo-fry": {"bitter_gourd": 300, "potato": 300, "mustard_oil": 35, "onion": 100},
    "parwal-fry": {"pointed_gourd": 400, "mustard_oil": 35, "turmeric": 5, "coriander_powder": 5},
    "parwal-aloo-rasila": {"pointed_gourd": 350, "potato": 300, "mustard_oil": 35, "tomato": 180},
    "chichinda-tarkari": {"snake_gourd": 450, "mustard_oil": 30, "cumin": 5, "turmeric": 5},
    "pharsi-ko-tarkari": {"pumpkin": 500, "mustard_oil": 30, "fenugreek_seeds": 2, "ginger": 10},
    "karkalo-gaura-tarkari": {"colocasia_leaves": 350, "mustard_oil": 30, "garlic": 20, "red_chili": 4},
    "pindalu-aloo-tarkari": {"colocasia": 400, "potato": 300, "mustard_oil": 35, "ajwain": 3},
    "ubaleko-tarul-sandheko": {"yam": 500, "mustard_oil": 25, "timur": 2, "green_chili": 10},
    "ubaleko-sakarkhanda": {"sweet_potato": 600},
    "kurilo-tarkari": {"asparagus": 300, "ghee": 30, "garlic": 15, "turmeric": 5},
    "chyau-tarkari": {"mushroom": 300, "onion": 120, "tomato": 200, "mustard_oil": 35, "garlic": 15},
    "chyau-aloo-jhol": {"mushroom": 250, "potato": 300, "mustard_oil": 35, "ginger": 15},
    "bakulla-ko-tarkari": {"potato": 350, "tomato": 200, "mustard_oil": 35, "garlic": 15},
    "bodi-aloo-jhol": {"bodi": 200, "potato": 350, "mustard_oil": 35, "tomato": 200},
    "baigun-bharta": {"eggplant": 500, "mustard_oil": 30, "garlic": 20, "green_chili": 15},
    "bhanta-aloo-tarkari": {"eggplant": 400, "potato": 300, "mustard_oil": 35, "fenugreek_seeds": 2},
    "banda-gobi-kerau": {"cabbage": 400, "green_peas": 150, "mustard_oil": 35, "turmeric": 5},
    "banda-aloo-tarkari": {"cabbage": 400, "potato": 350, "mustard_oil": 35, "ginger": 10},
    "masyaura-aloo-tarkari": {"masyaura": 150, "potato": 350, "tomato": 180, "mustard_oil": 35, "garlic": 15},
    "masyaura-cauliflower": {"masyaura": 150, "cauliflower": 400, "mustard_oil": 35, "ginger": 10},
    "paneer-mutter-nepali": {"paneer": 300, "green_peas": 150, "tomato": 200, "ghee": 40, "onion": 120},
    "paneer-palungo-jhol": {"paneer": 300, "spinach": 300, "ghee": 35, "garlic": 20, "ginger": 15},
    "gundruk-aloo-jhol": {"gundruk": 200, "potato": 350, "mustard_oil": 35, "garlic": 20, "tomato": 150},
    "sinki-aloo-jhol": {"sinki": 200, "potato": 350, "mustard_oil": 35, "garlic": 20},
    "mula-ko-tarkari": {"radish": 400, "mustard_oil": 30, "turmeric": 5, "fenugreek_seeds": 2},
    "mula-bodi-tarkari": {"radish": 350, "bodi": 150, "mustard_oil": 35, "ginger": 10},
    "karkalo-sinki-jhol": {"colocasia_leaves": 300, "sinki": 150, "mustard_oil": 30, "garlic": 20},
    "chyau-paneer-tarkari": {"mushroom": 250, "paneer": 250, "tomato": 200, "ghee": 35},
    "mixed-sabji-thali": {"cauliflower": 250, "potato": 250, "green_peas": 100, "french_beans": 150, "radish": 200},
    # --- saag ---
    "rayo-saag-tori": {"rayo_saag": 400, "mustard_oil": 30, "garlic": 25, "red_chili": 5},
    "palungo-saag-sadha": {"spinach": 400, "mustard_oil": 30, "garlic": 25},
    "chamsur-methi-saag": {"chamsur_saag": 300, "methi_saag": 150, "mustard_oil": 30, "garlic": 20},
    "tori-ko-saag-fry": {"rayo_saag": 400, "mustard_oil": 30, "red_chili": 4},
    "pharsi-munta-saag": {"pumpkin_shoots": 350, "mustard_oil": 30, "garlic": 20, "red_chili": 4},
    "karkalo-gaura-saag": {"colocasia_leaves": 400, "mustard_oil": 30, "garlic": 25},
    "mula-ko-saag": {"radish": 400, "mustard_oil": 30, "fenugreek_seeds": 2},
    "methi-saag-aloo": {"methi_saag": 300, "potato": 300, "mustard_oil": 35},
    "spinach-garlic-timmur": {"spinach": 400, "mustard_oil": 30, "timur": 2, "garlic": 20},
    "gundruk-saag-bhutuwa": {"gundruk": 250, "mustard_oil": 25, "green_chili": 15, "garlic": 15},
    # --- masu ---
    "khasiko-masu-jhol": {"goat_meat": 600, "mustard_oil": 50, "onion": 150, "ginger": 25, "garlic": 25, "tomato": 250},
    "khasiko-pakku": {"goat_meat": 800, "mustard_oil": 60, "cardamom": 5, "cinnamon": 3, "garlic": 30},
    "khasiko-bhutuwa": {"goat_meat": 600, "mustard_oil": 45, "onion": 150, "ginger": 20, "garlic": 20},
    "khasiko-ledobedo": {"goat_meat": 600, "onion": 200, "tomato": 250, "mustard_oil": 45, "garlic": 25},
    "khasiko-sekuwa": {"goat_meat": 700, "mustard_oil": 30, "timur": 3, "ginger": 20, "garlic": 20},
    "khasiko-sukuti-fry": {"goat_meat": 400, "mustard_oil": 40, "onion": 120, "green_chili": 15, "garlic": 15},
    "khasiko-sukuti-jhol": {"goat_meat": 400, "mustard_oil": 40, "tomato": 200, "garlic": 20, "timur": 2},
    "kukhura-ko-masu-jhol": {"chicken": 700, "mustard_oil": 50, "onion": 150, "tomato": 250, "ginger": 25, "garlic": 25},
    "kukhura-bhutuwa": {"chicken": 650, "mustard_oil": 45, "onion": 150, "ginger": 20, "garlic": 20},
    "kukhura-ledobedo": {"chicken": 650, "onion": 200, "tomato": 250, "mustard_oil": 45, "garlic": 25},
    "kukhura-chhoyela": {"chicken": 600, "mustard_oil": 40, "garlic": 30, "ginger": 25, "timur": 3, "fenugreek_seeds": 3},
    "ranga-ko-chhoyela": {"buff_meat": 600, "mustard_oil": 40, "garlic": 30, "ginger": 25, "timur": 3, "fenugreek_seeds": 3},
    "ranga-ko-kachila": {"buff_meat": 500, "mustard_oil": 30, "fenugreek_seeds": 4, "garlic": 20},
    "ranga-ko-bhutuwa": {"buff_meat": 600, "mustard_oil": 45, "onion": 150, "garlic": 20, "ginger": 20},
    "ranga-ko-jhol": {"buff_meat": 650, "mustard_oil": 50, "onion": 200, "tomato": 250, "garlic": 25},
    "machha-ko-jhol": {"fish": 600, "mustard_oil": 45, "tomato": 250, "garlic": 25, "ginger": 20},
    "machha-tareko": {"fish": 600, "mustard_oil": 50, "ajwain": 3, "turmeric": 5, "garlic": 20},
    "sukuti-sandheko": {"goat_meat": 400, "mustard_oil": 30, "onion": 150, "tomato": 200, "green_chili": 20, "timur": 3},
    "mutton-korma-nepali": {"goat_meat": 700, "yogurt": 250, "ghee": 60, "cardamom": 5, "cinnamon": 3},
    "kukhura-timur-roast": {"chicken": 700, "mustard_oil": 35, "timur": 3, "garlic": 25, "ginger": 20},
    # --- achar ---
    "golbheda-timur-achar": {"tomato": 600, "timur": 4, "green_chili": 30, "garlic": 40, "coriander_fresh": 30},
    "golbheda-til-achar": {"tomato": 600, "sesame": 40, "mustard_oil": 40, "green_chili": 30},
    "gundruk-sandheko": {"gundruk": 300, "mustard_oil": 30, "onion": 150, "tomato": 200, "green_chili": 25, "garlic": 25},
    "sinki-sandheko": {"sinki": 300, "mustard_oil": 30, "onion": 150, "green_chili": 25, "timur": 3},
    "mula-ko-achar-traditional": {"radish": 700, "mustard_oil": 40, "turmeric": 8, "red_chili": 10},
    "mula-kanche-achar": {"radish": 500, "mustard_oil": 40, "fenugreek_seeds": 3, "turmeric": 6, "green_chili": 25},
    "kakro-ko-achar": {"cucumber": 500, "sesame": 30, "mustard_oil": 35, "fenugreek_seeds": 2, "green_chili": 25},
    "aloo-ko-achar-nepali": {"potato": 600, "sesame": 30, "cucumber": 200, "mustard_oil": 45, "fenugreek_seeds": 3, "green_chili": 25},
    "timmur-ko-chhop": {"timur": 30, "red_chili": 60},
    "til-ko-chhop": {"sesame": 80, "red_chili": 40, "timur": 10},
    "lasun-khursani-chhop": {"garlic": 200, "red_chili": 80, "mustard_oil": 40},
    "lapsi-khatto-mittho-achar": {"lapsi": 500, "chaku": 200, "red_chili": 15, "mustard_oil": 40},
    "dallay-khursani-achar": {"green_chili": 500, "mustard_oil": 50, "garlic": 60},
    "karela-ko-achar": {"bitter_gourd": 500, "mustard_oil": 45, "turmeric": 8, "red_chili": 12},
    "aam-ko-khatto-achar": {"mustard_oil": 45, "fenugreek_seeds": 3, "turmeric": 8, "red_chili": 15},
    "nimbu-ko-achar": {"mustard_oil": 45, "turmeric": 8, "green_chili": 30, "fenugreek_seeds": 3},
    "bhatmas-sandheko": {"bhatmas": 300, "onion": 120, "tomato": 150, "green_chili": 25, "mustard_oil": 30},
    "alu-bodi-ko-achar": {"potato": 500, "bodi": 200, "sesame": 25, "mustard_oil": 45, "fenugreek_seeds": 3},
    # --- khaja ---
    "veg-momo-traditional": {"cabbage": 300, "paneer": 150, "onion": 100, "ginger": 15, "garlic": 15, "wheat_flour": 250},
    "chicken-momo-steamed": {"chicken": 350, "onion": 100, "ginger": 20, "garlic": 15, "wheat_flour": 250, "coriander_fresh": 20},
    "buff-momo-kathmandu": {"buff_meat": 400, "onion": 120, "ginger": 20, "garlic": 15, "wheat_flour": 280},
    "jhol-momo-achar": {"chicken": 300, "tomato": 400, "sesame": 30, "timur": 3, "wheat_flour": 250},
    "veg-chowmein-street": {"wheat_flour": 300, "cabbage": 250, "onion": 150, "green_chili": 20, "mustard_oil": 40},
    "chicken-chowmein": {"chicken": 350, "wheat_flour": 300, "cabbage": 250, "onion": 150, "mustard_oil": 40},
    "veg-thukpa-soup": {"wheat_flour": 250, "cabbage": 250, "radish": 200, "tomato": 250, "ginger": 20, "garlic": 20},
    "buff-thukpa-sherpa": {"buff_meat": 400, "wheat_flour": 250, "cabbage": 250, "garlic": 25, "timur": 3},
    "bara-wo-plain": {"kalo_dal": 250, "mustard_oil": 40, "ginger": 20, "garlic": 20},
    "bara-wo-egg": {"kalo_dal": 250, "mustard_oil": 40, "ginger": 20},
    "chataamari-plain": {"rice_flour": 250, "ghee": 40},
    "chataamari-keema": {"rice_flour": 250, "buff_meat": 300, "onion": 150, "green_chili": 20},
    "aloo-chop-nepali": {"potato": 500, "onion": 150, "garlic": 20, "mustard_oil": 40, "wheat_flour": 100},
    "pyaaz-pakoda": {"onion": 500, "green_chili": 25, "mustard_oil": 60},
    "cauliflower-pakoda": {"cauliflower": 450, "mustard_oil": 60, "turmeric": 6, "ajwain": 3},
    "nepali-samosa": {"wheat_flour": 300, "potato": 400, "green_peas": 150, "ghee": 50, "cumin": 5},
    "yomari-chaku": {"rice_flour": 300, "chaku": 250, "sesame": 40, "ghee": 50},
    "yomari-khuwa": {"rice_flour": 300, "milk": 400, "cardamom": 4},
    "gwaramari-newari": {"wheat_flour": 300, "ajwain": 4, "mustard_oil": 30},
    "samay-baji-set": {"chiura": 350, "kalo_dal": 200, "ginger": 25, "mustard_oil": 35, "garlic": 25},
    # --- roti_mithai ---
    "sel-roti-traditional": {"rice_flour": 400, "ghee": 80, "milk": 300, "cardamom": 4},
    "malpuwa-sweet": {"wheat_flour": 350, "milk": 350, "ghee": 70, "cardamom": [2, 1]},
    "kheer-nepali": {"rice": 120, "milk": 800, "ghee": 40, "cardamom": 4},
    "dar-kheer": {"rice": 150, "milk": 900, "ghee": 50, "cardamom": 4},
    "puri-festive": {"wheat_flour": 400, "ghee": 60},
    "phulka-roti": {"wheat_flour": 400},
    "kodo-ko-roti": {"millet_flour": 400, "ghee": 30},
    "phapar-ko-roti": {"buckwheat_flour": 400, "ghee": 30},
    "makai-ko-roti": {"wheat_flour": 400, "ghee": 30},
    "suji-ko-haluwa": {"semolina": 300, "ghee": 60, "milk": 300, "cardamom": 3},
    "til-ko-laddu": {"sesame": 300, "chaku": 250},
    "chaku-ghyu": {"chaku": 400, "ghee": 50},
    "thekuwa-chhath": {"wheat_flour": 350, "ghee": 60, "chaku": 250, "cardamom": 3},
    "anarsa-tihar": {"rice_flour": 350, "ghee": 70, "sesame": 50},
    "fini-roti-layered": {"wheat_flour": 400, "ghee": 100, "rice_flour": 150},
}
